services:

  #NODE
  node-web-projeto-ads-container:
    build:
      context: .
      dockerfile: docker/node22-web/Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
    restart: unless-stopped
    environment:
      - NODE_PORT=3000
      - IS_CONTAINER=TRUE
    expose:
      - ${NODE_PORT}
    networks:
      - projeto-ads-network
    depends_on:
      - postgres-container

  #NGINX
  nginx-container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - node-web-projeto-ads-container
    networks:
      - projeto-ads-network

  #POSTGRES
  postgres-container:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6789:${POSTGRES_PORT}"
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      projeto-ads-network:
        aliases:
          - ${POSTGRES_HOST}


#OTHERS

networks:
  projeto-ads-network:
    driver: bridge

volumes:
  pgdata-volume:
  node-modules-volume: